### ISSUE TITLE
WLED Error 10: Could not mount filesystem!

### ISSUE THREAD

**Issue by Elektroniker0486** [psxde/sp108e-led-controller#2]
Nach dem flashen von der WLED_0.13.0-b5_ESP8266.bin bekomme ich im WLED Webinterface den Fehler:

Error 10: Could not mount filesystem!

Der Controller funktioniert einwandfrei nur die WIFI und LED Einstellungen sind nach jedem reboot und Stromausfall immer wieder weg.
Hier im ioBroker Forum habe ich die Thematik geäußert.

https://forum.iobroker.net/topic/49963/sp108e-led-wifi-controller-wled-flashen

**Comment by psxde** [comment]
Hi @Elektroniker0486 ,

in dem anderen Beitrag scheinst du ja nun das Problem selbst gelöst zu haben.

Zur Vollständigkeit halber hier mein Stand:
- Die eingelöteten Brücken bleiben natürlich bestehen, denn damit wird der zweite Chip überbrückt und der ESP direkt an den LED-Strip gehängt.
- Der ESP8285 ist lediglich ein ESP8286 mit integriertem Flash-Speicher und benötigt keine Firmwareanpassung.
- Bei meinem Test hatte ich keine Auffälligkeiten/Fehler feststellen können. Getestet habe ich damals mit der Firmware v0.12.1-b1

**Comment by Elektroniker0486** [comment]
Ja, ich habe es gestern lösen können. Ich musste aber die ESP01 flashen. Die ESP8266 verursacht bei dem Chip den besagten Fehler. In dem SP108E ist ja ein ESP8285 verbaut.
 Trotzdem vielen dank!

**Comment by psxde** [comment]
Danke für deine Rückmeldung. Das liegt dann vermutlich daran, dass bei einem Standard-ESP von mehr verfügbarem Speicher ausgegangen wird. Für den SP108 mit 2MB habe ich mir selbst die Firmware compiliert und dafür damals folgende Einstellungen verwendet:

```
[env:sp108e]
board = esp8285
platform = ${common.platform_wled_default}
platform_packages = ${common.platform_packages}
board_build.ldscript = ${common.ldscript_2m512k}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags_esp8266} -D CLKPIN=13 -D LEDPIN=5 -D USE_APA102
```
