### ISSUE TITLE
Removing hardware modification after flashing

### ISSUE THREAD

**Issue by VladNord** [psxde/sp108e-led-controller#4]
Sorry for the noob question :)
Do I need remove hardware modification after flashing? 
Thanks!

**Comment by psxde** [comment]
Hi @VladNord,

you should remove the pinwires for flashing the firmware (rx/tx) but the other modifications need to persist

**Comment by VladNord** [comment]
> Hi @VladNord,
> 
> you should remove the pinwires for flashing the firmware (rx/tx) but the other modifications need to persist

Clear! thank you!
